import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';
import { round } from 'mathjs'

export default function Home() {
  const [value, setValue] = useState(1200);
  const [intrest, setIntrest] = useState(0.03)

  const handleChange = event => {
    setValue(12*event.target.value);

    console.log('value was:', value);
  };
  const handleChangeIntrest = event => {
    setIntrest(event.target.value / 100);

    console.log('value was:', intrest);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.wrapper}>
        <div className={styles.amountWrapper}>
          <label className={styles.amountLabel}> Månadsavgift</label>
      <input className={styles.amountInput} type="number" onChange={handleChange} placeholder={value/12}></input>
      </div>

      <div className={styles.intrestWrapper}>
        <label className={styles.intrestLabel}>
          Ränta (%)
        </label>
        <div className={styles.uselessDiv}>
      <input className={styles.intrestInput} step={0.1} type="number" onChange={handleChangeIntrest} placeholder={intrest*100}></input>
      </div>
      </div>

      <label className={styles.output}> {round(value/intrest).toLocaleString().replaceAll(","," ")} kr</label>
      <label className={styles.equation}> {round(value/intrest)} x {intrest*100}% = {value/12} x 12</label>
      <label className={styles.equationExp}> Kapital x ränta = Årsavgift</label>
      </div>

    </div>
  )
}
